version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"

    schedule:
      # daily / weekly / monthly 
      interval: "monthly"
      day: "friday"
      time: "12:00"

    open-pull-requests-limit: 5

    groups:
      github-actions:
        patterns:
          - "*"

    commit-message:
      prefix: "github-actions[bot]"

    labels:
      - "dependencies"
      - "github-actions"
